# Generated by Django 4.2 on 2024-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_account_bio_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, verbose_name='Featured Image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(verbose_name='Excerpt'),
        ),
    ]
