# Generated by Django 4.2 on 2024-12-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blogpost_featured_image_blogpost_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
